Make generated XML compatible with JUnit XSD
johnthagen/doxygen-junit pull request #1
Opened 2018-04-02 16:19 UTC by cordlandwehr

As defined e.g. in https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd
an error element must only have "type" and "message" properties. Thus,
the "line" and "file" properties must be set for the testcase object.

Using a malformed XML file in the current JUnit Jenkins plugin leads
to an internal plugin error with the result of an empty error list.

2018-04-03 01:44 UTC, johnthagen commented
@cordlandwehr Thanks for the PR, sounds like a good fix. This plugin was originally developed for Bamboo, but if this follows the official JUnit spec, it sounds like a good fix.

Travis failures are legit, please correct and then I think this will be good to merge.

2018-04-03 01:45 UTC, johnthagen requested changes
Please fix Travis failures.

2018-04-03 11:21 UTC, johnthagen commented
Looks like a unit test needs to be fixed due to your changes. Mind fixing that up?

You can test locally before pushing by running:

```
$ pip install tox
$ tox
```

2018-04-03 17:25 UTC, cordlandwehr commented
Thanks for the hint!

2018-04-03 21:55 UTC, johnthagen approved these changes

2018-04-03 21:55 UTC, johnthagen commented
Merged, thanks!

2018-04-03 21:56 UTC, merged

2018-04-03 22:11 UTC, johnthagen commented
@cordlandwehr Please confirm that [1.2.0](https://pypi.python.org/pypi/doxygen-junit/1.2.0) fixes your issue.

2018-04-07 08:35 UTC, cordlandwehr commented
@johnthagen I can confirm that 1.2.0 fixes all my issues on with the Jenkins integration